mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:issue_id>/vote/', views.vote, name='vote'),
    path('test', views.test, name='test'),

    
]

mysite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone 

#DateTimeField = datetimes
#CharField = character fields and requires max_length 
#ForeignKey = tells which tables are related to each other

class IssuesReported(models.Model): #This class represents a table that will represent all of the incoming and current issues on campus 
    issue_text = models.CharField(max_length = 280) #Won't accept strings > 280 Characters
    pub_date = models.DateTimeField('date published') #Dates reports of issues were sent

    def __str__(self):
        return self.issue_text 

class Users(models.Model): #This class represents users who reported issues
    user_name = models.ForeignKey(IssuesReported, on_delete=models.CASCADE) #Won't accept string > 25 Characters
    display_name = models.CharField(max_length = 100) # Won't accept string > 100 Characters
    votes = models.IntegerField(default=0)

  

mysite/polls/views.py
## Additional Notes Below

# request.POST is a dictionary-like object that lets you access submitted data by key name and its values are always strings 

# request.POST['choice'] returns ID of the selected choice, as a string. Also, raise KeyError if choice wasn't provided in POST data and redisplays the question form with an error messag if choice isn't given. 

# reverse() help avoid having to hardcode a URL in the view function 

# Create your views here.

from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Users, IssuesReported


#Home Page 

def test(request):
    #return HttpResponse("test")
    return render(request, 'polls/test.html')

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_issue_list'

    def get_queryset(self):
        # Return the last five published questions
        return IssuesReported.objects.order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = IssuesReported
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = IssuesReported
    template_name = 'polls/results.html'


def vote(request, question_id):
    user_name = get_object_or_404(IssuesReported, pk=question_id)
    try:
        selected_choice = IssuesReported.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Users.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'username': user_name,
            'error_message': "You didn't select a user name.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(user_name.id,)))

mysite/polls/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% block head %}
        <title>Base</title>
        {% endblock %}
    </head>
    <body>
        {% block body %}
            <h1>Base</h1>
        {% endblock %}
    </body>
</html>

mysite/polls/templates/polls/detail.html
test
<h1>{{ issuesreported.issue_text }}</h1>
<ul>
{% for issues in user_name.users_set.all %}
    <li>{{Users.display_name }}</li>
{% endfor %}
</ul>
  

mysite/polls/templates/polls/home.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html>
  <head>
      {% block head %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
      <meta name="generator" content="Jekyll v3.8.5">
      <title>Jumbotron Template · Bootstrap</title> 
      <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/jumbotron/"> 
  
      <!-- Bootstrap core CSS -->
   <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> 

  
  
      <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
          user-select: none;
      
        }

        /* .jumbotron {
          background-color:blue;
        } */
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
      </style> 
      <!-- Custom styles for this template -->
      <link href="jumbotron.css" rel="stylesheet">
      {%endblock%}

  </head>
  <body> 
      {% block body %}
      <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        
          <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="home.html">Home <span class="sr-only">(current)</span></a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="map.html">Report Concerns</a>
              </li>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="resources.html">Resources</a>
              </li>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="projects.html"> Projects and Initatives</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="http://127.0.0.1:8000/admin/login/?next=/admin/"> Admin Only </a>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
          </div>
        </nav>
        
        <main role="main">
        
          <!--Main jumbotron for a primary marketing message or call to action -->
          <div class="jumbotron">
            <div class="container">
              <h1 class="display-3">Welcome!</h1>
              <p>This is a website open to University of Michigan's community so that there is a resource to report concerns on campus in relation to accessibility and resouces on campus especially for those with disabilities.These resources can range from organizations to ongoing efforts and etc. </p>
              <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
            </div>
          </div>
        
          <div class="container"> 
           
            <!-- Report Concerns -->

            <div class="row">
              <div class="col-md-4">
                <h2>Report Concerns Here </h2>
                <p>Feel free to report concerns so it can be reported to correct department and addressed in a timely manner </p>
                <p><a class="btn btn-secondary" href="{% url 'map' %}" role="button">View details &raquo;</a></p>
              </div>
 
              <!-- Resources -->

              <div class="col-md-4">
                <h2>Resources</h2>
                <p>Student led and faculty/staff led organizations on campus are noted in this section and more info on Services for Students with Disabilities.  </p>
                <p><a class="btn btn-secondary" href="{% url 'resources' %}" role="button">View details &raquo;</a></p>
              </div>
          
              <!-- Projects -->
              
              <div class="col-md-4">
                  <h2>Current Projects and Initatives</h2>
                  <p> Current projects are included in this section and initiatives relating to disabilities</p>
                  <p><a class="btn btn-secondary" href="{% url 'projects' %}" role="button">View details &raquo;</a></p>
                </div>
            </div>
        
            <hr>
        
          </div> </container >
        
        </main>
        
        <footer class="container">
          <p>&copy; Company 2019</p>
        </footer>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
              <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
      {% endblock %}
  </body>
</html>

mysite/polls/templates/polls/index.html
{% if latest_issue_list %}
    <ul>
    {% for user_name in latest_issue_list %}
        <li><a href="{% url 'polls:detail' user_name.id %}">{{ user_name.issue_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ issue.issue_text }}</h1>

<ul>
{% for choice in issue.choice_set.all %}
    <li>{{ choice.display_name }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' issue.id %}">Vote again?</a>

mysite/polls/templates/polls/test.html
hello world